---
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- main
jobs:
  - job: buildjob
    displayName: Build and Package Game of life
    pool:
      name: default
    steps:
      - task: Maven@3
        inputs:
          mavenPOMFile: 'pom.xml'
          goal: 'package'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          jdkVersionOption: 'default'